# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: ecdb
  labels:
    app: ecdb
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: ecdb
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the master: ecdb-0.ecdb.
apiVersion: v1
kind: Service
metadata:
  name: ecdb-read
  labels:
    app: ecdb
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: ecdb