apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: command
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: command
        track: stable
        version: 1.0.0
    spec:
      containers:
      - name: command
        image: "cmlee1014/kubtest-command:latest"
        ports:
          - name: http
            containerPort: 80
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Kubernetes"
        volumeMounts:
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: command-secret-appsettings