apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: query
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: query
        track: stable
        version: 1.0.0
    spec:
      containers:
        - name: query
          image: "cmlee1014/kubtest-query:latest"
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 0.2
              memory: "50Mi"