apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: projection
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: projection
        track: stable
        version: 1.0.0
    spec:
      containers:
      - name: projection
        image: "cmlee1014/kubtest-projection:latest"
        ports:
          - name: http
            containerPort: 80
        resources:
          limits:
            cpu: 0.2
            memory: "50Mi"
        env:
        - name: "NODE_ENVIRONMENT"
          value: "Kubernetes"
        volumeMounts:
        - name: secrets
          mountPath: /usr/src/app/secrets
          readOnly: true
    volumes:
    - name: secrets
      secret:
        secretName: projection-secret-config